models:
  planner:    "anthropic:claude-opus-4-6"   # "openai:gpt-5.4"
  maker:      "anthropic:claude-haiku-4-5"  # "openai:gpt-5.4-nano"
  checker:    "anthropic:claude-sonnet-4-6" # "openai:gpt-5.4-mini"
  summarizer: "anthropic:claude-haiku-4-5"  # "openai:gpt-5.4-nano"


max_iterations:
  planner: 20
  maker: 20
  checker: 10
  summarizer: 5
  maker_checker_cycles: 5 # if issues remain after n cycles, inform user

checker:
  tools:
    - "uv run ruff check --fix"
    - "uv run ruff format"
    - "uv run ty check"
    - "uv run pytest"
